export { default as Colors } from './colors'
export { default as Dimens } from './dimens'
export { default as samples } from './sample.json'
export { default as Icon } from './icons'
export { default as Images } from './images'
